### ISSUE TITLE
incompatiblity error

### ISSUE THREAD

**Issue by Lensman-86** [E1Camino/foundryvtt-vtm-20th#3]
Hi. when installing this in foundry version 0.7., I am getting an incompatibility error, that says some features may not work. Is there any way you could update this to the latest stable release of foundry?

**Comment by GiGaJo** [comment]
Hi.
I can have a look at it, probably next week.
Although development is still very early in the process and the module itself is nowhere close to being fully playable.

**Comment by E1Camino** [comment]
This module should work now with Foundry VTT 0.7.5
